### ISSUE TITLE
Accounts removal questions and TODOs

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#1521]
The related PR: https://github.com/iotaledger/iota-sdk/pull/1279

Questions:
- [x] Do we need both [`WalletData`](https://github.com/iotaledger/iota-sdk/blob/2.0/sdk/src/wallet/core/mod.rs#L105) and [`WalletInner`](https://github.com/iotaledger/iota-sdk/blob/2.0/sdk/src/wallet/core/mod.rs#L82)? yes, but it should be renamed (#1903)
- [x] Should [`WalletData::bip_path`](https://github.com/iotaledger/iota-sdk/blob/2.0/sdk/src/wallet/core/mod.rs#L107) really be optional ? yes, but the `WalletBuilder` should be changed (#1904)
- [x] Do we really want to propagate the single address everywhere? (yes for now)
- [x] Do we really want to remove [`RemainderValueStrategy::ChangeAddress`](https://github.com/iotaledger/iota-sdk/blob/2.0/sdk/src/wallet/operations/transaction/options.rs#L47)? (yes for now)
- [x] Do we want [`WalletBuilder::with_address`](https://github.com/iotaledger/iota-sdk/blob/2.0/sdk/src/wallet/core/builder.rs#L75)? (no, needs change: #1904)
- [x] Should we remove `get_addresses_to_sync` and similar functionality? (fn already removed?, but [`here`](https://github.com/iotaledger/iota-sdk/blob/2.0/sdk/src/wallet/operations/syncing/mod.rs#L104) is where we're requiring it)
- [x] Do we still need [`AddressWithUnspentOutputs`](https://github.com/iotaledger/iota-sdk/blob/2.0/sdk/src/wallet/types/address.rs#L52)? (yes, but simplified: #1905)
- [x] Should we keep [`bech32_hrp`](https://github.com/iotaledger/iota-sdk/blob/2.0/sdk/src/wallet/core/mod.rs#L451) from Account in `Wallet`, and [`get_bech32_hrp`](https://github.com/iotaledger/iota-sdk/blob/2.0/sdk/src/client/core.rs#L151) ? (yes)

Questions (CLI):
- [x] Merge both enums: [`WalletCommand`](https://github.com/iotaledger/iota-sdk/blob/2.0/cli/src/wallet_cli/mod.rs#L57) [`CliCommand`](https://github.com/iotaledger/iota-sdk/blob/2.0/cli/src/cli.rs#L111) or just rename them? (no)
- [x] Should we bring back `addresses`/`new-address` [`command`](https://github.com/iotaledger/iota-sdk/blob/2.0/cli/src/wallet_cli/mod.rs#L57)? (no for now)
- [x] Do we really want `InitParameters` Bip44 parsing the way it is [here](https://github.com/iotaledger/iota-sdk/blob/2.0/cli/src/cli.rs#L67)? (yes for now)
- [x] Remove address from [`InitParameters`](https://github.com/iotaledger/iota-sdk/blob/2.0/cli/src/cli.rs#L71)? (sort of yes, #1904)
- [x] Bring back `addresses_balance` method? There is [`WalletCommand::Balance`](https://github.com/iotaledger/iota-sdk/blob/2.0/cli/src/wallet_cli/mod.rs#L65) (yes, #1907 )

Todos:
- [x] Reorganise examples (in what way?) (skipped)
- [x] Reorganise CLI (yes, #1908 ) 
- [x] Rename `accounts_and_addresses` examples (#1909)
- [x] Rename `WalletData` (yes, #1903)
- [x] Uncomment/fix tests (#1910)
- [x] Adapt the storage keys in `sdk/src/wallet/storage/constants.rs` (constants look good)

Potential bugs:
- [x] Removing `account_addresses` and `account_and_nft_addresses` from `can_output_be_unlocked_now` just seems wrong (#1911)

**Comment by thibault-martinez** [comment]
Has been split into different issues
