### ISSUE TITLE
(WIP) NodeJs features epic

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-sdk#1559]
```[tasklist]
### SDK
- [x] Single account wallet (https://github.com/iotaledger/iota-sdk/pull/1580)
- [x] Rename block types (https://github.com/iotaledger/iota-sdk/pull/1706)
- [x] Updated events (https://github.com/iotaledger/iota-sdk/pull/1789)
```

```[tasklist]
### Implicit account outputs
- [x] ImplicitAccountCreationAddress generation (https://github.com/iotaledger/iota-sdk/pull/1556)
- [x] List implicit accounts (https://github.com/iotaledger/iota-sdk/pull/1574)
- [x] Implicit account transition (https://github.com/iotaledger/iota-sdk/pull/1598)
```

```[tasklist]
### Account outputs
- [x] List accounts (https://github.com/iotaledger/iota-sdk/pull/1583)
- [x] Select account as default block issuer
- [x] Get default block issuer
- [x] Transfer account ownership
- [x] Delete account
```

```[tasklist]
### Delegation
- [x] List delegations
- [x] Potential rewards
- [x] Claim rewards
```

```[tasklist]
### Utilities
- [x] Mana waiting time estimation for transition
```

**Comment by thibault-martinez** [comment]
All done :)
